name: "Maven Dependency Submission"
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
jobs:
  submit-dependencies:
    if: github.repository == 'bhoradc/aws-sdk-java-v2'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: advanced-security/maven-dependency-submission-action@v5
        with:
          maven-args: >-
            -DtransitiveExcludes=*:*
            -DclasspathScope=runtime
            -pl !build-tools,!release-scripts,!archetypes,!test/test-utils,!test/sdk-benchmarks,!test/http-client-tests,!test/http-client-benchmarks,!test/s3-benchmarks,!test/protocol-tests-core,!test/ruleset-testing-core,!test/protocol-tests,!test/service-test-utils,!test/codegen-generated-classes-test,!test/sdk-standard-benchmarks,!test/module-path-tests,!test/tests-coverage-reporting,!test/stability-tests,!test/sdk-native-image-test,!test/auth-tests,!test/region-testing,!test/old-client-version-compatibility-test,!test/bundle-logging-bridge-binding-test,!test/v2-migration-tests,!test/bundle-shading-tests,!test/crt-unavailable-tests,!test/architecture-tests,!test/s3-tests
